# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 23:24
from __future__ import unicode_literals

import apps.loginreg_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpassword',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45, validators=[apps.loginreg_app.models.validateGTtwo]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, validators=[apps.loginreg_app.models.validateGTtwo]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[apps.loginreg_app.models.validateGTfour]),
        ),
    ]
