# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplans',
            name='travel_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travelplans',
            name='travel_start',
            field=models.DateField(),
        ),
    ]
